services:
  backend:
    build: ./backend
    container_name: ${BACKEND_CONTAINER_NAME}
    networks:
      - ${DOCKER_NETWORK_NAME}
  
  nginx:
    image: nginx:${NGINX_VERSION}
    container_name: ${NGINX_CONTAINER_NAME}
    ports:
     - 80:80
    volumes:
     - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - backend
    networks:
      - ${DOCKER_NETWORK_NAME}

networks:
  app-network:
    driver: ${DOCKER_NETWORK_DRIVER}